### ISSUE TITLE
[Feature Request] Adding or Removing Biomes

### ISSUE THREAD

**Issue by kriNon** [WerDei/Biome-Replacer#14]
Hey,
I'm working on a modpack for 1.20.1, and I've been looking for some ways where I can add or remove entire biomes to specific dimensions. I was wondering if it would be challenging to add this functionality based on how Biome-Replacer works.

Thanks!

**Comment by WerDei** [comment]
Straight up addition of biomes wouldn't be possible, I'm sorry to say. Since Caves and Cliffs update the biome generation became very complex, and it became very tricky for modders to add new ones. I'm certainly not smart enough to figure out a painless solution.

Still, you might try adding a datapack with new biomes, then simply replace the ones you don't like with the ones you need (that's the use case I made the mod for). The other, more complex solution, is to use other mods - for example, [Biome Squisher](https://modrinth.com/mod/biomesquisher) allows inserting new biomes using a datapack. Or the classic, [Terra Blender](https://github.com/Glitchfiend/TerraBlender/wiki/Getting-started) (though you might need to make a mod to use it).
