### ISSUE TITLE
not working on 1.20.6 forge/fabric

### ISSUE THREAD

**Issue by Diamondcreepah** [WerDei/Biome-Replacer#24]
I tried pretty much everything at this point. at first I thought it was an issue with forge, then with tectonic, but both turned out to do nothing. the mod still doesn't replace anything.

# Put your rules here in the format:
# old_biome > new_biome
# 
# Examples (remove # in front of one to activate it):
# minecraft:dark_forest > minecraft:cherry_grove
# terralith:lavender_forest > aurorasdeco:lavender_plains
# terralith:lavender_valley > aurorasdeco:lavender_plains
# terralith:cave/infested_caves > minecraft:dripstone_caves
minecraft:ice_spikes > minecraft:snowy_plains
minecraft:mushroom_fields > minecraft_plains
minecraft:mangrove_swamp > minecraft_swamp
minecraft:deep_dark > minecraft:dripstone_caves
minecraft:frozen_ocean > minecraft:ocean
minecraft:lush_caves > minecraft:dripstone_caves
minecraft:dark_forest > minecraft:taiga

[2024-12-24-5.log](https://github.com/user-attachments/files/18241558/2024-12-24-5.log)

**Comment by WerDei** [comment]
That's very strange - according to the log, there are no rules in the config file? Make sure you are actually editing a correct file. 
Meanwhile, I'll try backporting the never BR version, since it works very differently to 1.2 and may work out better for you.

**Comment by WerDei** [comment]
Backport done - please try the new 1.7 version, and let me know wether it fixed the problem

**Comment by Diamondcreepah** [comment]
installed the 1.7 version as listed on modrinth, but the issue still persists. I also tried deleting and rewriting the config file, but nothing seems to work. the only thing I can think of is that the mod is somehow incompatible with certain optimization mods, but I really cannot afford to 

[2024-12-27-3.log](https://github.com/user-attachments/files/18261561/2024-12-27-3.log)
[2024-12-27-4.log](https://github.com/user-attachments/files/18261563/2024-12-27-4.log)
![Schermafbeelding 2024-12-27 163045](https://github.com/user-attachments/assets/9954e3bf-57ac-435f-9fd9-403ef4763639)

**Comment by WerDei** [comment]
Weird question to start - did you remember to save the file after you edited it? Asking because I see a gray dot in your text editor tab, which usually indicates unsaved changes.

If that wasn't the problem, then I'm officially stumped. I've tried installing every mod you have down to the exact version (found from the logs), and could not reproduce the issue. It's unlikely to be a mod incompatibility anyway, since BR should at least log how many rules it loaded before breaking. In your case it's logging 0, which can't be right.

You can try to update your mods (many of them are outdated, I noticed) just to see if anything changes, but otherwise I'm out of ideas.

**Comment by Diamondcreepah** [comment]
actually saving the file (forgive my stupidity) seems to have worked.... somewhat. I tested it on 5 clean worlds and 5 out of 7 biomes have apparently been eliminated.  however, mangrove swamps and mushroom fields keep consistently ignoring the set configs. as far as I'm aware there are no mistakes in the config, nor have I changed its contents after rewriting it to 1.7.
![2024-12-28_01 50 36](https://github.com/user-attachments/assets/507a3878-2a64-40b0-9095-4aa4e8f9b256)

**Comment by Diamondcreepah** [comment]
the logs however show that there are still no rules being applied, which does confuse me a little...
[2024-12-27-5.log](https://github.com/user-attachments/files/18264534/2024-12-27-5.log)

**Comment by WerDei** [comment]
Well, glad to hear the fix was simple, haha! I also see the issue with the last two biomes - when specifying replacements, you used a `_` where a `:` should be - so instead of `minecraft_plains` it should be `minecraft:plains`, for example.

The fact that logs *still* don't work is even stranger, but I guess it's not a problem if the mod works as intended

**Comment by Diamondcreepah** [comment]
oh, so it was a fault on my part :D thank you for the support, I'l much enjoy using this mod for a long time to come!
